# Dependencies
markdown:	redcarpet
baseurl: /blog
pygments:	true
exclude: ["README.md"]
# Permalinks
permalink:	/blog/:title

# Setup
title:		Romin991
tagline:	'blog'
description:	'My personal blog.'
url:		http://romin991.github.io/blog

author:
  name:		'Romin Adi Santoso'
  url:		https://google.com/+romin991

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/romin991
    desc:	Follow me on twitter

  - icon:	github
    url:	https://github.com/romin991
    desc:	Fork me on github

  - icon:	googleplus-alt
    url:	https://google.com/+romin991
    desc:	Add me on google+

 
    
menu:
  - title:	Home
    url:	/
    
  - title:	About
    url:	/
    
copyright:
  author:	Romin Adi Santoso
  url:		http://romin991.github.io/blog
  type_title:	Some rights reserved
  type_url:	http://creativecommons.org/licenses/by-nc/2.5
